matrix:
  include:
  - language: ruby
    rvm: 2.6.3
    sudo: false
    cache: bandler
    before_script:
    - cd rubocop
    - gem install bundler
    - bundle install --path vendor/bundle
    script:
    - bundle exec rake rubocop
    deploy:
      provider: rubygems
      api_key: SOON-SOON-SOON
      gemspec: rubocop.gemspec
      on:
        branch: master
