matrix:
  include:
  - language: ruby
    rvm: 2.7.1
    sudo: false
    cache: bundler
    before_script:
    - cd rubocop
    - gem install bundler
    - bundle install --path vendor/bundle
    script:
    - bundle exec rake rubocop
    deploy:
      api_key:
        secure: CMir32FaECfH8Ja2lqHYitn3LeFKscSHb9+hR5qeMQPQjxm4HmPo6Kj4lP8uXf6ExOHQfBrHOG8++F9Er6oiWK7bAPFhQ4nZHvpe61f2KERJH21ICkd2+MdYFe+7s5c/Dxw9+bVahCsPsX4+lRn7ShV8rpSMBJ8hZJA27yibkdszeXiYtWCGxQuGjgq7PDeGP/SZ2iAx9D3mdthUiRcAmUWwY8DQMsGd5gt7UwRWSauqwOp38iRm4S7TJGOloOKtUftMUBmQrpTWK1cxtxW749yjrP/9UrFpquaV7pC6muq1JzXcOy76eWg3GMoIRtBEAyHsjRis+JMgh8sqyADFOLam60ivJmJVEJW5Bx5PtI2C5UnG0ihXmd4gaIezsscYRg0U9ilQMtsmNNlZkdiOvIJgLP8m9Zc/eNocH/dxRjRFBixXLfZ2L9Y5yK8evrMKqmxoZr5RJxyxgQXuWTpUIcmz08eObOBoHA7wxH7cecmOEDnk0tDa4b9/ObSo4Jvy7HHE21zpk9PQnHeuKIabDhHV6HzTF3AHxNoA+6oNjOSF4jH4zdZ/idMM19+e4JFdd1HmhWqGq43HlBk1+Fm8I1MFVpPVlstbxb7u/OtFoHzbphl04k0xn1QRES2nATTBwlj0itNXBJ9prX4WCV2Ev1El27xfhPiBs/tF7cCIcYs=
      provider: rubygems
      gemspec: rubocop.gemspec
      on:
        repo: umbrellio/code-style
        branch: master
