# frozen_string_literal: true

require "bundler/gem_tasks"
require "rubocop/rake_task"
require "rubocop"
require "rubocop-performance"
require "rubocop-rspec"

RuboCop::RakeTask.new(:rubocop) do |t|
  t.options = %w[--config ./.rubocop.yml]
  t.plugins << "rubocop-rspec"
  t.plugins << "rubocop-performance"
end

task default: :rubocop
