rules:
  # Colors
  color-hex-case: lower
  color-hex-length: short
  color-named: never
  color-no-hex: null
  color-no-invalid-hex: true
  # Fonts
  font-family-name-quotes: always-where-recommended
  font-family-no-duplicate-names: true
  font-weight-notation: null
  # Functions
  function-calc-no-unspaced-operator: true
  function-comma-newline-after: null
  function-comma-newline-before: null
  function-comma-space-after: always
  function-comma-space-before: never
  function-linear-gradient-no-nonstandard-direction: true
  function-max-empty-lines: 0
  function-name-case: lower
  function-parentheses-newline-inside: null
  function-parentheses-space-inside: never
  function-url-data-uris: null
  function-url-no-scheme-relative: true
  function-url-quotes:
    - always
    - except: empty
  function-whitespace-after: always
  # Numbers
  number-leading-zero: never
  number-max-precision: null
  number-no-trailing-zeros: true
  # Strings
  string-no-newline: true
  string-quotes: single
  # Length
  length-zero-no-unit: true
  # Time
  time-min-milliseconds: null
  # Units
  unit-case: lower
  unit-no-unknown: true
  # Values
  value-keyword-case: lower
  value-no-vendor-prefix: null
  value-list-comma-newline-after: null
  value-list-comma-newline-before: null
  value-list-comma-space-after: always
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0
  # Properties
  custom-property-empty-line-before: never
  shorthand-property-no-redundant-values: true
  property-case: lower
  property-no-unknown: true
  property-no-vendor-prefix: null
  # Declarations
  keyframe-declaration-no-important: null
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-colon-newline-after: always-multi-line
  declaration-colon-space-after: always
  declaration-colon-space-before: never
  declaration-empty-line-before: null
  declaration-no-important: null
  declaration-block-no-duplicate-properties:
    - true
    - ignore: consecutive-duplicates-with-different-values
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-after: always-single-line
  declaration-block-semicolon-space-before: never
  declaration-block-single-line-max-declarations: 1
  declaration-block-trailing-semicolon: always
  # Blocks
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after: always
  block-closing-brace-newline-before: always-multi-line
  block-closing-brace-space-after: null
  block-closing-brace-space-before: null
  block-no-empty: null
  block-opening-brace-newline-after: always-multi-line
  block-opening-brace-newline-before: null
  # Selectors
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-attribute-quotes: always
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  selector-pseudo-class-case: lower
  selector-pseudo-class-no-unknown: true
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: single
  selector-pseudo-element-no-unknown: true
  selector-type-case: lower
  selector-type-no-unknown: true
  selector-max-empty-lines: 0
  selector-list-comma-newline-after: null
  selector-list-comma-newline-before: null
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never
  # Rules
  rule-empty-line-before:
    - null # temporary (change to 'always' later)
    - ignore:
      - after-comment
      - inside-block
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  media-feature-name-case: lower
  media-feature-name-no-unknown: true
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always
  media-query-list-comma-space-after: always
  media-query-list-comma-space-before: never
  at-rule-empty-line-before:
    - always
    - except:
      - after-same-name
      - inside-block
  at-rule-name-case: lower
  at-rule-name-space-after: always
  at-rule-no-unknown: true
  at-rule-semicolon-newline-after: always
  at-rule-semicolon-space-before: never
  # Comments
  comment-no-empty: true
  comment-whitespace-inside: always
  # General
  indentation: 2
  max-empty-lines: 1
  max-nesting-depth: 6
  max-line-length: 100
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  no-missing-end-of-source-newline: true
  no-unknown-animations: true
