name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run on push event
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'umbrellio/code-style'

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3
        bundler-cache: true
        working-directory: rubocop

    - run: cd rubocop && bundle exec rake

  release-gem:
    runs-on: ubuntu-latest
    environment: Deploy

    permissions:
      id-token: write
      contents: write

    # Run on push to master branch
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
          working-directory: rubocop

      - uses: rubygems/release-gem@v1
        working-directory: rubocop

